/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.14.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *actionCreate;
    QAction *actionOpen;
    QAction *actionSave;
    QAction *actionSave_Us;
    QAction *actionExit;
    QWidget *centralwidget;
    QTableWidget *shop_table_widget;
    QTableWidget *prod_table_search_widget;
    QLabel *shop_label;
    QLabel *prod_label;
    QPushButton *shop_add_button;
    QPushButton *shop_del_button;
    QLabel *shop_name_label;
    QLineEdit *shop_name_line_edit;
    QLineEdit *shop_address_line_edit;
    QLabel *shop_address_label;
    QLabel *shop_phone_label;
    QLineEdit *shop_phone_line_edit;
    QPushButton *prod_add_button;
    QPushButton *prod_del_button;
    QRadioButton *bread_radioButton;
    QRadioButton *pastry_radioButton;
    QRadioButton *bakery_radioButton;
    QLineEdit *prod_price_line_edit;
    QLabel *prod_price_label;
    QLabel *prod_mass_label;
    QLineEdit *prod_mass_line_edit;
    QLabel *prod_count_label;
    QLineEdit *prod_count_line_edit;
    QLabel *prod_sugar_label;
    QLineEdit *prod_sugar_line_edit;
    QLabel *prod_powder_label;
    QLineEdit *prod_powder_line_edit;
    QLabel *prod_form_label;
    QLineEdit *prod_form_line_edit;
    QLineEdit *prod_roasting_line_edit;
    QLabel *prod_roasting_label;
    QFrame *line;
    QFrame *line_2;
    QFrame *line_3;
    QFrame *line_4;
    QFrame *line_5;
    QFrame *line_6;
    QFrame *line_7;
    QFrame *line_8;
    QFrame *line_9;
    QFrame *line_10;
    QFrame *line_11;
    QFrame *line_12;
    QLineEdit *prod_dough_line_edit;
    QLabel *prod_dough_label;
    QLineEdit *prod_additive_line_edit;
    QLabel *prod_additive_label;
    QLineEdit *prod_num_line_edit;
    QLabel *prod_num_label;
    QTableWidget *prod_table_widget;
    QPushButton *prod_accept_button;
    QPushButton *shop_accept_button;
    QLabel *prod_selectshop_label;
    QFrame *line_13;
    QFrame *line_14;
    QFrame *line_15;
    QComboBox *prod_selectshop_combobox;
    QFrame *line_16;
    QPushButton *prod_searchaccept_button;
    QFrame *line_17;
    QComboBox *prod_searchtype_combobox;
    QFrame *line_18;
    QFrame *line_20;
    QFrame *line_19;
    QLineEdit *prod_typesearch_line_edit;
    QLabel *prod_type_label;
    QPushButton *prod_search_button;
    QLabel *prod_num_label_2;
    QLineEdit *prod_numsearch_line_edit;
    QPushButton *shop_edit_button;
    QMenuBar *menubar;
    QMenu *menu;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->setEnabled(true);
        MainWindow->resize(1077, 676);
        actionCreate = new QAction(MainWindow);
        actionCreate->setObjectName(QString::fromUtf8("actionCreate"));
        actionOpen = new QAction(MainWindow);
        actionOpen->setObjectName(QString::fromUtf8("actionOpen"));
        actionSave = new QAction(MainWindow);
        actionSave->setObjectName(QString::fromUtf8("actionSave"));
        actionSave_Us = new QAction(MainWindow);
        actionSave_Us->setObjectName(QString::fromUtf8("actionSave_Us"));
        actionExit = new QAction(MainWindow);
        actionExit->setObjectName(QString::fromUtf8("actionExit"));
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        shop_table_widget = new QTableWidget(centralwidget);
        if (shop_table_widget->columnCount() < 3)
            shop_table_widget->setColumnCount(3);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        shop_table_widget->setHorizontalHeaderItem(0, __qtablewidgetitem);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        shop_table_widget->setHorizontalHeaderItem(1, __qtablewidgetitem1);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        shop_table_widget->setHorizontalHeaderItem(2, __qtablewidgetitem2);
        shop_table_widget->setObjectName(QString::fromUtf8("shop_table_widget"));
        shop_table_widget->setGeometry(QRect(10, 30, 321, 371));
        prod_table_search_widget = new QTableWidget(centralwidget);
        if (prod_table_search_widget->columnCount() < 12)
            prod_table_search_widget->setColumnCount(12);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        prod_table_search_widget->setHorizontalHeaderItem(0, __qtablewidgetitem3);
        QTableWidgetItem *__qtablewidgetitem4 = new QTableWidgetItem();
        prod_table_search_widget->setHorizontalHeaderItem(1, __qtablewidgetitem4);
        QTableWidgetItem *__qtablewidgetitem5 = new QTableWidgetItem();
        prod_table_search_widget->setHorizontalHeaderItem(2, __qtablewidgetitem5);
        QTableWidgetItem *__qtablewidgetitem6 = new QTableWidgetItem();
        prod_table_search_widget->setHorizontalHeaderItem(3, __qtablewidgetitem6);
        QTableWidgetItem *__qtablewidgetitem7 = new QTableWidgetItem();
        prod_table_search_widget->setHorizontalHeaderItem(4, __qtablewidgetitem7);
        QTableWidgetItem *__qtablewidgetitem8 = new QTableWidgetItem();
        prod_table_search_widget->setHorizontalHeaderItem(5, __qtablewidgetitem8);
        QTableWidgetItem *__qtablewidgetitem9 = new QTableWidgetItem();
        prod_table_search_widget->setHorizontalHeaderItem(6, __qtablewidgetitem9);
        QTableWidgetItem *__qtablewidgetitem10 = new QTableWidgetItem();
        prod_table_search_widget->setHorizontalHeaderItem(7, __qtablewidgetitem10);
        QTableWidgetItem *__qtablewidgetitem11 = new QTableWidgetItem();
        prod_table_search_widget->setHorizontalHeaderItem(8, __qtablewidgetitem11);
        QTableWidgetItem *__qtablewidgetitem12 = new QTableWidgetItem();
        prod_table_search_widget->setHorizontalHeaderItem(9, __qtablewidgetitem12);
        QTableWidgetItem *__qtablewidgetitem13 = new QTableWidgetItem();
        prod_table_search_widget->setHorizontalHeaderItem(10, __qtablewidgetitem13);
        QTableWidgetItem *__qtablewidgetitem14 = new QTableWidgetItem();
        prod_table_search_widget->setHorizontalHeaderItem(11, __qtablewidgetitem14);
        prod_table_search_widget->setObjectName(QString::fromUtf8("prod_table_search_widget"));
        prod_table_search_widget->setGeometry(QRect(360, 30, 711, 311));
        shop_label = new QLabel(centralwidget);
        shop_label->setObjectName(QString::fromUtf8("shop_label"));
        shop_label->setGeometry(QRect(10, 10, 81, 16));
        QFont font;
        font.setFamily(QString::fromUtf8("Calibri"));
        font.setPointSize(13);
        shop_label->setFont(font);
        prod_label = new QLabel(centralwidget);
        prod_label->setObjectName(QString::fromUtf8("prod_label"));
        prod_label->setGeometry(QRect(360, 10, 81, 16));
        prod_label->setFont(font);
        shop_add_button = new QPushButton(centralwidget);
        shop_add_button->setObjectName(QString::fromUtf8("shop_add_button"));
        shop_add_button->setGeometry(QRect(10, 410, 111, 41));
        QFont font1;
        font1.setFamily(QString::fromUtf8("Calibri"));
        font1.setPointSize(10);
        font1.setBold(true);
        font1.setWeight(75);
        shop_add_button->setFont(font1);
        shop_del_button = new QPushButton(centralwidget);
        shop_del_button->setObjectName(QString::fromUtf8("shop_del_button"));
        shop_del_button->setEnabled(false);
        shop_del_button->setGeometry(QRect(130, 410, 111, 41));
        shop_del_button->setFont(font1);
        shop_name_label = new QLabel(centralwidget);
        shop_name_label->setObjectName(QString::fromUtf8("shop_name_label"));
        shop_name_label->setEnabled(false);
        shop_name_label->setGeometry(QRect(20, 490, 71, 16));
        QFont font2;
        font2.setFamily(QString::fromUtf8("Calibri"));
        font2.setPointSize(11);
        shop_name_label->setFont(font2);
        shop_name_line_edit = new QLineEdit(centralwidget);
        shop_name_line_edit->setObjectName(QString::fromUtf8("shop_name_line_edit"));
        shop_name_line_edit->setEnabled(false);
        shop_name_line_edit->setGeometry(QRect(100, 490, 111, 20));
        shop_address_line_edit = new QLineEdit(centralwidget);
        shop_address_line_edit->setObjectName(QString::fromUtf8("shop_address_line_edit"));
        shop_address_line_edit->setEnabled(false);
        shop_address_line_edit->setGeometry(QRect(100, 520, 111, 20));
        shop_address_label = new QLabel(centralwidget);
        shop_address_label->setObjectName(QString::fromUtf8("shop_address_label"));
        shop_address_label->setEnabled(false);
        shop_address_label->setGeometry(QRect(20, 520, 71, 16));
        shop_address_label->setFont(font2);
        shop_phone_label = new QLabel(centralwidget);
        shop_phone_label->setObjectName(QString::fromUtf8("shop_phone_label"));
        shop_phone_label->setEnabled(false);
        shop_phone_label->setGeometry(QRect(20, 550, 71, 16));
        shop_phone_label->setFont(font2);
        shop_phone_line_edit = new QLineEdit(centralwidget);
        shop_phone_line_edit->setObjectName(QString::fromUtf8("shop_phone_line_edit"));
        shop_phone_line_edit->setEnabled(false);
        shop_phone_line_edit->setGeometry(QRect(100, 550, 111, 20));
        prod_add_button = new QPushButton(centralwidget);
        prod_add_button->setObjectName(QString::fromUtf8("prod_add_button"));
        prod_add_button->setEnabled(true);
        prod_add_button->setGeometry(QRect(490, 410, 51, 41));
        QFont font3;
        font3.setFamily(QString::fromUtf8("Calibri"));
        font3.setPointSize(25);
        font3.setBold(true);
        font3.setWeight(75);
        prod_add_button->setFont(font3);
        prod_del_button = new QPushButton(centralwidget);
        prod_del_button->setObjectName(QString::fromUtf8("prod_del_button"));
        prod_del_button->setEnabled(true);
        prod_del_button->setGeometry(QRect(550, 410, 51, 41));
        prod_del_button->setFont(font3);
        bread_radioButton = new QRadioButton(centralwidget);
        bread_radioButton->setObjectName(QString::fromUtf8("bread_radioButton"));
        bread_radioButton->setEnabled(false);
        bread_radioButton->setGeometry(QRect(620, 410, 82, 41));
        bread_radioButton->setFont(font2);
        bread_radioButton->setChecked(true);
        pastry_radioButton = new QRadioButton(centralwidget);
        pastry_radioButton->setObjectName(QString::fromUtf8("pastry_radioButton"));
        pastry_radioButton->setEnabled(false);
        pastry_radioButton->setGeometry(QRect(700, 410, 201, 41));
        pastry_radioButton->setFont(font2);
        pastry_radioButton->setChecked(false);
        bakery_radioButton = new QRadioButton(centralwidget);
        bakery_radioButton->setObjectName(QString::fromUtf8("bakery_radioButton"));
        bakery_radioButton->setEnabled(false);
        bakery_radioButton->setGeometry(QRect(900, 410, 181, 41));
        bakery_radioButton->setFont(font2);
        prod_price_line_edit = new QLineEdit(centralwidget);
        prod_price_line_edit->setObjectName(QString::fromUtf8("prod_price_line_edit"));
        prod_price_line_edit->setEnabled(false);
        prod_price_line_edit->setGeometry(QRect(710, 510, 111, 20));
        prod_price_label = new QLabel(centralwidget);
        prod_price_label->setObjectName(QString::fromUtf8("prod_price_label"));
        prod_price_label->setEnabled(false);
        prod_price_label->setGeometry(QRect(620, 510, 71, 16));
        prod_price_label->setFont(font2);
        prod_mass_label = new QLabel(centralwidget);
        prod_mass_label->setObjectName(QString::fromUtf8("prod_mass_label"));
        prod_mass_label->setEnabled(false);
        prod_mass_label->setGeometry(QRect(620, 540, 71, 16));
        prod_mass_label->setFont(font2);
        prod_mass_line_edit = new QLineEdit(centralwidget);
        prod_mass_line_edit->setObjectName(QString::fromUtf8("prod_mass_line_edit"));
        prod_mass_line_edit->setEnabled(false);
        prod_mass_line_edit->setGeometry(QRect(710, 540, 111, 20));
        prod_count_label = new QLabel(centralwidget);
        prod_count_label->setObjectName(QString::fromUtf8("prod_count_label"));
        prod_count_label->setEnabled(false);
        prod_count_label->setGeometry(QRect(620, 570, 81, 16));
        prod_count_label->setFont(font2);
        prod_count_line_edit = new QLineEdit(centralwidget);
        prod_count_line_edit->setObjectName(QString::fromUtf8("prod_count_line_edit"));
        prod_count_line_edit->setEnabled(false);
        prod_count_line_edit->setGeometry(QRect(710, 570, 111, 20));
        prod_sugar_label = new QLabel(centralwidget);
        prod_sugar_label->setObjectName(QString::fromUtf8("prod_sugar_label"));
        prod_sugar_label->setEnabled(false);
        prod_sugar_label->setGeometry(QRect(840, 510, 71, 16));
        prod_sugar_label->setFont(font2);
        prod_sugar_line_edit = new QLineEdit(centralwidget);
        prod_sugar_line_edit->setObjectName(QString::fromUtf8("prod_sugar_line_edit"));
        prod_sugar_line_edit->setEnabled(false);
        prod_sugar_line_edit->setGeometry(QRect(930, 510, 111, 20));
        prod_powder_label = new QLabel(centralwidget);
        prod_powder_label->setObjectName(QString::fromUtf8("prod_powder_label"));
        prod_powder_label->setEnabled(false);
        prod_powder_label->setGeometry(QRect(840, 540, 91, 16));
        prod_powder_label->setFont(font2);
        prod_powder_line_edit = new QLineEdit(centralwidget);
        prod_powder_line_edit->setObjectName(QString::fromUtf8("prod_powder_line_edit"));
        prod_powder_line_edit->setEnabled(false);
        prod_powder_line_edit->setGeometry(QRect(930, 540, 111, 20));
        prod_form_label = new QLabel(centralwidget);
        prod_form_label->setObjectName(QString::fromUtf8("prod_form_label"));
        prod_form_label->setEnabled(false);
        prod_form_label->setGeometry(QRect(840, 570, 91, 16));
        prod_form_label->setFont(font2);
        prod_form_line_edit = new QLineEdit(centralwidget);
        prod_form_line_edit->setObjectName(QString::fromUtf8("prod_form_line_edit"));
        prod_form_line_edit->setEnabled(false);
        prod_form_line_edit->setGeometry(QRect(930, 570, 111, 20));
        prod_roasting_line_edit = new QLineEdit(centralwidget);
        prod_roasting_line_edit->setObjectName(QString::fromUtf8("prod_roasting_line_edit"));
        prod_roasting_line_edit->setEnabled(false);
        prod_roasting_line_edit->setGeometry(QRect(930, 600, 111, 20));
        prod_roasting_label = new QLabel(centralwidget);
        prod_roasting_label->setObjectName(QString::fromUtf8("prod_roasting_label"));
        prod_roasting_label->setEnabled(false);
        prod_roasting_label->setGeometry(QRect(840, 600, 91, 16));
        prod_roasting_label->setFont(font2);
        line = new QFrame(centralwidget);
        line->setObjectName(QString::fromUtf8("line"));
        line->setEnabled(false);
        line->setGeometry(QRect(610, 450, 461, 21));
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);
        line_2 = new QFrame(centralwidget);
        line_2->setObjectName(QString::fromUtf8("line_2"));
        line_2->setEnabled(false);
        line_2->setGeometry(QRect(5, 465, 221, 31));
        line_2->setFrameShape(QFrame::HLine);
        line_2->setFrameShadow(QFrame::Sunken);
        line_3 = new QFrame(centralwidget);
        line_3->setObjectName(QString::fromUtf8("line_3"));
        line_3->setEnabled(false);
        line_3->setGeometry(QRect(5, 570, 221, 21));
        line_3->setFrameShape(QFrame::HLine);
        line_3->setFrameShadow(QFrame::Sunken);
        line_4 = new QFrame(centralwidget);
        line_4->setObjectName(QString::fromUtf8("line_4"));
        line_4->setEnabled(false);
        line_4->setGeometry(QRect(210, 480, 31, 101));
        line_4->setFrameShape(QFrame::VLine);
        line_4->setFrameShadow(QFrame::Sunken);
        line_5 = new QFrame(centralwidget);
        line_5->setObjectName(QString::fromUtf8("line_5"));
        line_5->setEnabled(false);
        line_5->setGeometry(QRect(610, 620, 461, 20));
        line_5->setFrameShape(QFrame::HLine);
        line_5->setFrameShadow(QFrame::Sunken);
        line_6 = new QFrame(centralwidget);
        line_6->setObjectName(QString::fromUtf8("line_6"));
        line_6->setEnabled(false);
        line_6->setGeometry(QRect(600, 460, 20, 171));
        line_6->setFrameShape(QFrame::VLine);
        line_6->setFrameShadow(QFrame::Sunken);
        line_7 = new QFrame(centralwidget);
        line_7->setObjectName(QString::fromUtf8("line_7"));
        line_7->setEnabled(false);
        line_7->setGeometry(QRect(610, 436, 461, 31));
        line_7->setFrameShape(QFrame::HLine);
        line_7->setFrameShadow(QFrame::Sunken);
        line_8 = new QFrame(centralwidget);
        line_8->setObjectName(QString::fromUtf8("line_8"));
        line_8->setEnabled(false);
        line_8->setGeometry(QRect(610, 396, 461, 31));
        line_8->setFrameShape(QFrame::HLine);
        line_8->setFrameShadow(QFrame::Sunken);
        line_9 = new QFrame(centralwidget);
        line_9->setObjectName(QString::fromUtf8("line_9"));
        line_9->setEnabled(true);
        line_9->setGeometry(QRect(594, 410, 31, 41));
        line_9->setFrameShape(QFrame::VLine);
        line_9->setFrameShadow(QFrame::Sunken);
        line_10 = new QFrame(centralwidget);
        line_10->setObjectName(QString::fromUtf8("line_10"));
        line_10->setEnabled(true);
        line_10->setGeometry(QRect(1061, 410, 20, 41));
        line_10->setFrameShape(QFrame::VLine);
        line_10->setFrameShadow(QFrame::Sunken);
        line_11 = new QFrame(centralwidget);
        line_11->setObjectName(QString::fromUtf8("line_11"));
        line_11->setEnabled(true);
        line_11->setGeometry(QRect(1060, 460, 20, 171));
        line_11->setFrameShape(QFrame::VLine);
        line_11->setFrameShadow(QFrame::Sunken);
        line_12 = new QFrame(centralwidget);
        line_12->setObjectName(QString::fromUtf8("line_12"));
        line_12->setEnabled(true);
        line_12->setGeometry(QRect(-10, 480, 31, 101));
        line_12->setFrameShape(QFrame::VLine);
        line_12->setFrameShadow(QFrame::Sunken);
        prod_dough_line_edit = new QLineEdit(centralwidget);
        prod_dough_line_edit->setObjectName(QString::fromUtf8("prod_dough_line_edit"));
        prod_dough_line_edit->setEnabled(false);
        prod_dough_line_edit->setGeometry(QRect(710, 600, 111, 20));
        prod_dough_label = new QLabel(centralwidget);
        prod_dough_label->setObjectName(QString::fromUtf8("prod_dough_label"));
        prod_dough_label->setEnabled(false);
        prod_dough_label->setGeometry(QRect(620, 600, 91, 16));
        prod_dough_label->setFont(font2);
        prod_additive_line_edit = new QLineEdit(centralwidget);
        prod_additive_line_edit->setObjectName(QString::fromUtf8("prod_additive_line_edit"));
        prod_additive_line_edit->setEnabled(false);
        prod_additive_line_edit->setGeometry(QRect(930, 480, 111, 20));
        prod_additive_label = new QLabel(centralwidget);
        prod_additive_label->setObjectName(QString::fromUtf8("prod_additive_label"));
        prod_additive_label->setEnabled(false);
        prod_additive_label->setGeometry(QRect(840, 480, 91, 16));
        prod_additive_label->setFont(font2);
        prod_num_line_edit = new QLineEdit(centralwidget);
        prod_num_line_edit->setObjectName(QString::fromUtf8("prod_num_line_edit"));
        prod_num_line_edit->setEnabled(false);
        prod_num_line_edit->setGeometry(QRect(710, 480, 111, 20));
        prod_num_label = new QLabel(centralwidget);
        prod_num_label->setObjectName(QString::fromUtf8("prod_num_label"));
        prod_num_label->setEnabled(false);
        prod_num_label->setGeometry(QRect(620, 480, 71, 16));
        prod_num_label->setFont(font2);
        prod_table_widget = new QTableWidget(centralwidget);
        if (prod_table_widget->columnCount() < 12)
            prod_table_widget->setColumnCount(12);
        QTableWidgetItem *__qtablewidgetitem15 = new QTableWidgetItem();
        prod_table_widget->setHorizontalHeaderItem(0, __qtablewidgetitem15);
        QTableWidgetItem *__qtablewidgetitem16 = new QTableWidgetItem();
        prod_table_widget->setHorizontalHeaderItem(1, __qtablewidgetitem16);
        QTableWidgetItem *__qtablewidgetitem17 = new QTableWidgetItem();
        prod_table_widget->setHorizontalHeaderItem(2, __qtablewidgetitem17);
        QTableWidgetItem *__qtablewidgetitem18 = new QTableWidgetItem();
        prod_table_widget->setHorizontalHeaderItem(3, __qtablewidgetitem18);
        QTableWidgetItem *__qtablewidgetitem19 = new QTableWidgetItem();
        prod_table_widget->setHorizontalHeaderItem(4, __qtablewidgetitem19);
        QTableWidgetItem *__qtablewidgetitem20 = new QTableWidgetItem();
        prod_table_widget->setHorizontalHeaderItem(5, __qtablewidgetitem20);
        QTableWidgetItem *__qtablewidgetitem21 = new QTableWidgetItem();
        prod_table_widget->setHorizontalHeaderItem(6, __qtablewidgetitem21);
        QTableWidgetItem *__qtablewidgetitem22 = new QTableWidgetItem();
        prod_table_widget->setHorizontalHeaderItem(7, __qtablewidgetitem22);
        QTableWidgetItem *__qtablewidgetitem23 = new QTableWidgetItem();
        prod_table_widget->setHorizontalHeaderItem(8, __qtablewidgetitem23);
        QTableWidgetItem *__qtablewidgetitem24 = new QTableWidgetItem();
        prod_table_widget->setHorizontalHeaderItem(9, __qtablewidgetitem24);
        QTableWidgetItem *__qtablewidgetitem25 = new QTableWidgetItem();
        prod_table_widget->setHorizontalHeaderItem(10, __qtablewidgetitem25);
        QTableWidgetItem *__qtablewidgetitem26 = new QTableWidgetItem();
        prod_table_widget->setHorizontalHeaderItem(11, __qtablewidgetitem26);
        prod_table_widget->setObjectName(QString::fromUtf8("prod_table_widget"));
        prod_table_widget->setGeometry(QRect(360, 30, 711, 311));
        prod_accept_button = new QPushButton(centralwidget);
        prod_accept_button->setObjectName(QString::fromUtf8("prod_accept_button"));
        prod_accept_button->setEnabled(false);
        prod_accept_button->setGeometry(QRect(460, 590, 141, 41));
        QFont font4;
        font4.setFamily(QString::fromUtf8("Calibri"));
        font4.setPointSize(16);
        font4.setBold(true);
        font4.setWeight(75);
        prod_accept_button->setFont(font4);
        shop_accept_button = new QPushButton(centralwidget);
        shop_accept_button->setObjectName(QString::fromUtf8("shop_accept_button"));
        shop_accept_button->setEnabled(false);
        shop_accept_button->setGeometry(QRect(10, 590, 121, 41));
        shop_accept_button->setFont(font4);
        prod_selectshop_label = new QLabel(centralwidget);
        prod_selectshop_label->setObjectName(QString::fromUtf8("prod_selectshop_label"));
        prod_selectshop_label->setEnabled(false);
        prod_selectshop_label->setGeometry(QRect(420, 553, 81, 21));
        prod_selectshop_label->setFont(font2);
        line_13 = new QFrame(centralwidget);
        line_13->setObjectName(QString::fromUtf8("line_13"));
        line_13->setEnabled(false);
        line_13->setGeometry(QRect(408, 542, 191, 16));
        line_13->setFrameShape(QFrame::HLine);
        line_13->setFrameShadow(QFrame::Sunken);
        line_14 = new QFrame(centralwidget);
        line_14->setObjectName(QString::fromUtf8("line_14"));
        line_14->setEnabled(false);
        line_14->setGeometry(QRect(408, 573, 191, 16));
        line_14->setFrameShape(QFrame::HLine);
        line_14->setFrameShadow(QFrame::Sunken);
        line_15 = new QFrame(centralwidget);
        line_15->setObjectName(QString::fromUtf8("line_15"));
        line_15->setEnabled(false);
        line_15->setGeometry(QRect(388, 550, 41, 31));
        line_15->setFrameShape(QFrame::VLine);
        line_15->setFrameShadow(QFrame::Sunken);
        prod_selectshop_combobox = new QComboBox(centralwidget);
        prod_selectshop_combobox->setObjectName(QString::fromUtf8("prod_selectshop_combobox"));
        prod_selectshop_combobox->setEnabled(false);
        prod_selectshop_combobox->setGeometry(QRect(500, 554, 91, 22));
        line_16 = new QFrame(centralwidget);
        line_16->setObjectName(QString::fromUtf8("line_16"));
        line_16->setEnabled(false);
        line_16->setGeometry(QRect(580, 550, 41, 31));
        line_16->setFrameShape(QFrame::VLine);
        line_16->setFrameShadow(QFrame::Sunken);
        prod_searchaccept_button = new QPushButton(centralwidget);
        prod_searchaccept_button->setObjectName(QString::fromUtf8("prod_searchaccept_button"));
        prod_searchaccept_button->setEnabled(false);
        prod_searchaccept_button->setGeometry(QRect(564, 510, 31, 31));
        QFont font5;
        font5.setFamily(QString::fromUtf8("Calibri"));
        font5.setPointSize(13);
        font5.setBold(false);
        font5.setWeight(50);
        font5.setKerning(false);
        prod_searchaccept_button->setFont(font5);
        prod_searchaccept_button->setIconSize(QSize(16, 16));
        prod_searchaccept_button->setCheckable(false);
        prod_searchaccept_button->setAutoRepeatDelay(300);
        prod_searchaccept_button->setAutoRepeatInterval(100);
        line_17 = new QFrame(centralwidget);
        line_17->setObjectName(QString::fromUtf8("line_17"));
        line_17->setEnabled(false);
        line_17->setGeometry(QRect(591, 458, 16, 83));
        line_17->setFrameShape(QFrame::VLine);
        line_17->setFrameShadow(QFrame::Sunken);
        prod_searchtype_combobox = new QComboBox(centralwidget);
        prod_searchtype_combobox->addItem(QString());
        prod_searchtype_combobox->addItem(QString());
        prod_searchtype_combobox->addItem(QString());
        prod_searchtype_combobox->setObjectName(QString::fromUtf8("prod_searchtype_combobox"));
        prod_searchtype_combobox->setEnabled(false);
        prod_searchtype_combobox->setGeometry(QRect(416, 461, 86, 31));
        prod_searchtype_combobox->setEditable(false);
        line_18 = new QFrame(centralwidget);
        line_18->setObjectName(QString::fromUtf8("line_18"));
        line_18->setEnabled(false);
        line_18->setGeometry(QRect(408, 531, 191, 22));
        line_18->setFrameShape(QFrame::HLine);
        line_18->setFrameShadow(QFrame::Sunken);
        line_20 = new QFrame(centralwidget);
        line_20->setObjectName(QString::fromUtf8("line_20"));
        line_20->setEnabled(true);
        line_20->setGeometry(QRect(408, 450, 191, 16));
        line_20->setFrameShape(QFrame::HLine);
        line_20->setFrameShadow(QFrame::Sunken);
        line_19 = new QFrame(centralwidget);
        line_19->setObjectName(QString::fromUtf8("line_19"));
        line_19->setEnabled(false);
        line_19->setGeometry(QRect(400, 458, 16, 84));
        line_19->setFrameShape(QFrame::VLine);
        line_19->setFrameShadow(QFrame::Sunken);
        prod_typesearch_line_edit = new QLineEdit(centralwidget);
        prod_typesearch_line_edit->setObjectName(QString::fromUtf8("prod_typesearch_line_edit"));
        prod_typesearch_line_edit->setEnabled(false);
        prod_typesearch_line_edit->setGeometry(QRect(460, 495, 101, 21));
        prod_type_label = new QLabel(centralwidget);
        prod_type_label->setObjectName(QString::fromUtf8("prod_type_label"));
        prod_type_label->setEnabled(false);
        prod_type_label->setGeometry(QRect(415, 495, 31, 16));
        QFont font6;
        font6.setFamily(QString::fromUtf8("Calibri"));
        font6.setPointSize(10);
        prod_type_label->setFont(font6);
        prod_search_button = new QPushButton(centralwidget);
        prod_search_button->setObjectName(QString::fromUtf8("prod_search_button"));
        prod_search_button->setEnabled(false);
        prod_search_button->setGeometry(QRect(510, 460, 86, 33));
        QFont font7;
        font7.setFamily(QString::fromUtf8("Calibri"));
        font7.setPointSize(13);
        font7.setBold(true);
        font7.setWeight(75);
        prod_search_button->setFont(font7);
        prod_num_label_2 = new QLabel(centralwidget);
        prod_num_label_2->setObjectName(QString::fromUtf8("prod_num_label_2"));
        prod_num_label_2->setEnabled(false);
        prod_num_label_2->setGeometry(QRect(415, 520, 41, 16));
        prod_num_label_2->setFont(font6);
        prod_numsearch_line_edit = new QLineEdit(centralwidget);
        prod_numsearch_line_edit->setObjectName(QString::fromUtf8("prod_numsearch_line_edit"));
        prod_numsearch_line_edit->setEnabled(false);
        prod_numsearch_line_edit->setGeometry(QRect(460, 519, 101, 21));
        shop_edit_button = new QPushButton(centralwidget);
        shop_edit_button->setObjectName(QString::fromUtf8("shop_edit_button"));
        shop_edit_button->setEnabled(false);
        shop_edit_button->setGeometry(QRect(250, 410, 81, 41));
        shop_edit_button->setFont(font1);
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 1077, 21));
        menu = new QMenu(menubar);
        menu->setObjectName(QString::fromUtf8("menu"));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);

        menubar->addAction(menu->menuAction());
        menu->addAction(actionCreate);
        menu->addAction(actionOpen);
        menu->addAction(actionSave);
        menu->addAction(actionSave_Us);
        menu->addAction(actionExit);

        retranslateUi(MainWindow);

        prod_searchtype_combobox->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "MainWindow", nullptr));
        actionCreate->setText(QCoreApplication::translate("MainWindow", "Create", nullptr));
        actionOpen->setText(QCoreApplication::translate("MainWindow", "Open", nullptr));
        actionSave->setText(QCoreApplication::translate("MainWindow", "Save", nullptr));
        actionSave_Us->setText(QCoreApplication::translate("MainWindow", "Save As", nullptr));
        actionExit->setText(QCoreApplication::translate("MainWindow", "Exit", nullptr));
        QTableWidgetItem *___qtablewidgetitem = shop_table_widget->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QCoreApplication::translate("MainWindow", "\320\235\320\260\320\267\320\262\320\260\320\275\320\270\320\265", nullptr));
        QTableWidgetItem *___qtablewidgetitem1 = shop_table_widget->horizontalHeaderItem(1);
        ___qtablewidgetitem1->setText(QCoreApplication::translate("MainWindow", "\320\220\320\264\321\200\320\265\321\201", nullptr));
        QTableWidgetItem *___qtablewidgetitem2 = shop_table_widget->horizontalHeaderItem(2);
        ___qtablewidgetitem2->setText(QCoreApplication::translate("MainWindow", "\320\242\320\265\320\273\320\265\321\204\320\276\320\275", nullptr));
        QTableWidgetItem *___qtablewidgetitem3 = prod_table_search_widget->horizontalHeaderItem(0);
        ___qtablewidgetitem3->setText(QCoreApplication::translate("MainWindow", "\320\235\320\276\320\274\320\265\321\200", nullptr));
        QTableWidgetItem *___qtablewidgetitem4 = prod_table_search_widget->horizontalHeaderItem(1);
        ___qtablewidgetitem4->setText(QCoreApplication::translate("MainWindow", "\320\242\320\270\320\277", nullptr));
        QTableWidgetItem *___qtablewidgetitem5 = prod_table_search_widget->horizontalHeaderItem(2);
        ___qtablewidgetitem5->setText(QCoreApplication::translate("MainWindow", "\320\234\320\260\320\263\320\260\320\267\320\270\320\275", nullptr));
        QTableWidgetItem *___qtablewidgetitem6 = prod_table_search_widget->horizontalHeaderItem(3);
        ___qtablewidgetitem6->setText(QCoreApplication::translate("MainWindow", "\320\246\320\265\320\275\320\260", nullptr));
        QTableWidgetItem *___qtablewidgetitem7 = prod_table_search_widget->horizontalHeaderItem(4);
        ___qtablewidgetitem7->setText(QCoreApplication::translate("MainWindow", "\320\234\320\260\321\201\321\201\320\260", nullptr));
        QTableWidgetItem *___qtablewidgetitem8 = prod_table_search_widget->horizontalHeaderItem(5);
        ___qtablewidgetitem8->setText(QCoreApplication::translate("MainWindow", "\320\232\320\276\320\273-\320\262\320\276", nullptr));
        QTableWidgetItem *___qtablewidgetitem9 = prod_table_search_widget->horizontalHeaderItem(6);
        ___qtablewidgetitem9->setText(QCoreApplication::translate("MainWindow", "\320\242\320\265\321\201\321\202\320\276", nullptr));
        QTableWidgetItem *___qtablewidgetitem10 = prod_table_search_widget->horizontalHeaderItem(7);
        ___qtablewidgetitem10->setText(QCoreApplication::translate("MainWindow", "\320\224\320\276\320\261\320\260\320\262\320\272\320\260", nullptr));
        QTableWidgetItem *___qtablewidgetitem11 = prod_table_search_widget->horizontalHeaderItem(8);
        ___qtablewidgetitem11->setText(QCoreApplication::translate("MainWindow", "% \320\241\320\260\321\205\320\260\321\200\320\260", nullptr));
        QTableWidgetItem *___qtablewidgetitem12 = prod_table_search_widget->horizontalHeaderItem(9);
        ___qtablewidgetitem12->setText(QCoreApplication::translate("MainWindow", "\320\232\320\276\320\273-\320\262\320\276 \320\277\321\203\320\264\321\200\321\213", nullptr));
        QTableWidgetItem *___qtablewidgetitem13 = prod_table_search_widget->horizontalHeaderItem(10);
        ___qtablewidgetitem13->setText(QCoreApplication::translate("MainWindow", "\320\244\320\276\321\200\320\274\320\260", nullptr));
        QTableWidgetItem *___qtablewidgetitem14 = prod_table_search_widget->horizontalHeaderItem(11);
        ___qtablewidgetitem14->setText(QCoreApplication::translate("MainWindow", "\320\236\320\261\320\266\320\260\321\200\320\272\320\260", nullptr));
        shop_label->setText(QCoreApplication::translate("MainWindow", "\320\234\320\260\320\263\320\260\320\267\320\270\320\275\321\213:", nullptr));
        prod_label->setText(QCoreApplication::translate("MainWindow", "\320\242\320\276\320\262\320\260\321\200\321\213:", nullptr));
        shop_add_button->setText(QCoreApplication::translate("MainWindow", "\320\224\320\276\320\261\320\260\320\262\320\270\321\202\321\214 \320\274\320\260\320\263\320\260\320\267\320\270\320\275", nullptr));
        shop_del_button->setText(QCoreApplication::translate("MainWindow", "\320\243\320\264\320\260\320\273\320\270\321\202\321\214 \320\274\320\260\320\263\320\260\320\267\320\270\320\275", nullptr));
        shop_name_label->setText(QCoreApplication::translate("MainWindow", "\320\235\320\260\320\267\320\262\320\260\320\275\320\270\320\265:", nullptr));
        shop_address_label->setText(QCoreApplication::translate("MainWindow", "\320\220\320\264\321\200\320\265\321\201:", nullptr));
        shop_phone_label->setText(QCoreApplication::translate("MainWindow", "\320\242\320\265\320\273\320\265\321\204\320\276\320\275:", nullptr));
        prod_add_button->setText(QCoreApplication::translate("MainWindow", "+", nullptr));
        prod_del_button->setText(QCoreApplication::translate("MainWindow", "-", nullptr));
        bread_radioButton->setText(QCoreApplication::translate("MainWindow", "\320\245\320\273\320\265\320\261", nullptr));
        pastry_radioButton->setText(QCoreApplication::translate("MainWindow", "\320\232\320\276\320\275\320\264\320\270\321\202\320\265\321\200\321\201\320\272\320\276\320\265 \320\270\320\267\320\264\320\265\320\273\320\270\320\265", nullptr));
        bakery_radioButton->setText(QCoreApplication::translate("MainWindow", "\320\221\321\203\320\273\320\276\321\207\320\275\320\276\320\265 \320\270\320\267\320\264\320\265\320\273\320\270\320\265", nullptr));
        prod_price_line_edit->setText(QString());
        prod_price_label->setText(QCoreApplication::translate("MainWindow", "\320\246\320\265\320\275\320\260:", nullptr));
        prod_mass_label->setText(QCoreApplication::translate("MainWindow", "\320\234\320\260\321\201\321\201\320\260:", nullptr));
        prod_mass_line_edit->setText(QString());
        prod_count_label->setText(QCoreApplication::translate("MainWindow", "\320\232\320\276\320\273\320\270\321\207\320\265\321\201\321\202\320\262\320\276:", nullptr));
        prod_count_line_edit->setText(QString());
        prod_sugar_label->setText(QCoreApplication::translate("MainWindow", "% \320\241\320\260\321\205\320\260\321\200\320\260:", nullptr));
        prod_sugar_line_edit->setText(QString());
        prod_powder_label->setText(QCoreApplication::translate("MainWindow", "\320\232\320\276\320\273. \320\277\321\203\320\264\321\200\321\213:", nullptr));
        prod_powder_line_edit->setText(QString());
        prod_form_label->setText(QCoreApplication::translate("MainWindow", "\320\244\320\276\321\200\320\274\320\260:", nullptr));
        prod_form_line_edit->setText(QString());
        prod_roasting_line_edit->setText(QString());
        prod_roasting_label->setText(QCoreApplication::translate("MainWindow", "\320\236\320\261\320\266\320\260\321\200\320\272\320\260:", nullptr));
        prod_dough_line_edit->setText(QString());
        prod_dough_label->setText(QCoreApplication::translate("MainWindow", "\320\242\320\265\321\201\321\202\320\276:", nullptr));
        prod_additive_line_edit->setText(QString());
        prod_additive_label->setText(QCoreApplication::translate("MainWindow", "\320\224\320\276\320\261\320\260\320\262\320\272\320\260:", nullptr));
        prod_num_line_edit->setText(QString());
        prod_num_label->setText(QCoreApplication::translate("MainWindow", "\320\235\320\276\320\274\320\265\321\200:", nullptr));
        QTableWidgetItem *___qtablewidgetitem15 = prod_table_widget->horizontalHeaderItem(0);
        ___qtablewidgetitem15->setText(QCoreApplication::translate("MainWindow", "\320\235\320\276\320\274\320\265\321\200", nullptr));
        QTableWidgetItem *___qtablewidgetitem16 = prod_table_widget->horizontalHeaderItem(1);
        ___qtablewidgetitem16->setText(QCoreApplication::translate("MainWindow", "\320\242\320\270\320\277", nullptr));
        QTableWidgetItem *___qtablewidgetitem17 = prod_table_widget->horizontalHeaderItem(2);
        ___qtablewidgetitem17->setText(QCoreApplication::translate("MainWindow", "\320\234\320\260\320\263\320\260\320\267\320\270\320\275", nullptr));
        QTableWidgetItem *___qtablewidgetitem18 = prod_table_widget->horizontalHeaderItem(3);
        ___qtablewidgetitem18->setText(QCoreApplication::translate("MainWindow", "\320\246\320\265\320\275\320\260", nullptr));
        QTableWidgetItem *___qtablewidgetitem19 = prod_table_widget->horizontalHeaderItem(4);
        ___qtablewidgetitem19->setText(QCoreApplication::translate("MainWindow", "\320\234\320\260\321\201\321\201\320\260", nullptr));
        QTableWidgetItem *___qtablewidgetitem20 = prod_table_widget->horizontalHeaderItem(5);
        ___qtablewidgetitem20->setText(QCoreApplication::translate("MainWindow", "\320\232\320\276\320\273-\320\262\320\276", nullptr));
        QTableWidgetItem *___qtablewidgetitem21 = prod_table_widget->horizontalHeaderItem(6);
        ___qtablewidgetitem21->setText(QCoreApplication::translate("MainWindow", "\320\242\320\265\321\201\321\202\320\276", nullptr));
        QTableWidgetItem *___qtablewidgetitem22 = prod_table_widget->horizontalHeaderItem(7);
        ___qtablewidgetitem22->setText(QCoreApplication::translate("MainWindow", "\320\224\320\276\320\261\320\260\320\262\320\272\320\260", nullptr));
        QTableWidgetItem *___qtablewidgetitem23 = prod_table_widget->horizontalHeaderItem(8);
        ___qtablewidgetitem23->setText(QCoreApplication::translate("MainWindow", "% \320\241\320\260\321\205\320\260\321\200\320\260", nullptr));
        QTableWidgetItem *___qtablewidgetitem24 = prod_table_widget->horizontalHeaderItem(9);
        ___qtablewidgetitem24->setText(QCoreApplication::translate("MainWindow", "\320\232\320\276\320\273-\320\262\320\276 \320\277\321\203\320\264\321\200\321\213", nullptr));
        QTableWidgetItem *___qtablewidgetitem25 = prod_table_widget->horizontalHeaderItem(10);
        ___qtablewidgetitem25->setText(QCoreApplication::translate("MainWindow", "\320\244\320\276\321\200\320\274\320\260", nullptr));
        QTableWidgetItem *___qtablewidgetitem26 = prod_table_widget->horizontalHeaderItem(11);
        ___qtablewidgetitem26->setText(QCoreApplication::translate("MainWindow", "\320\236\320\261\320\266\320\260\321\200\320\272\320\260", nullptr));
        prod_accept_button->setText(QCoreApplication::translate("MainWindow", "\320\237\321\200\320\270\320\275\321\217\321\202\321\214", nullptr));
        shop_accept_button->setText(QCoreApplication::translate("MainWindow", "\320\237\321\200\320\270\320\275\321\217\321\202\321\214", nullptr));
        prod_selectshop_label->setText(QCoreApplication::translate("MainWindow", "\320\234\320\260\320\263\320\260\320\267\320\270\320\275:", nullptr));
        prod_searchaccept_button->setText(QCoreApplication::translate("MainWindow", "\360\237\224\215\357\270\216", nullptr));
#if QT_CONFIG(shortcut)
        prod_searchaccept_button->setShortcut(QString());
#endif // QT_CONFIG(shortcut)
        prod_searchtype_combobox->setItemText(0, QCoreApplication::translate("MainWindow", "\320\235\320\276\320\274\320\265\321\200", nullptr));
        prod_searchtype_combobox->setItemText(1, QCoreApplication::translate("MainWindow", "\320\242\320\270\320\277", nullptr));
        prod_searchtype_combobox->setItemText(2, QCoreApplication::translate("MainWindow", "\320\234\320\260\320\263\320\260\320\267\320\270\320\275", nullptr));

        prod_searchtype_combobox->setCurrentText(QCoreApplication::translate("MainWindow", "\320\235\320\276\320\274\320\265\321\200", nullptr));
        prod_typesearch_line_edit->setText(QString());
        prod_type_label->setText(QCoreApplication::translate("MainWindow", "\320\242\320\270\320\277:", nullptr));
        prod_search_button->setText(QCoreApplication::translate("MainWindow", "\320\237\320\276\320\270\321\201\320\272", nullptr));
        prod_num_label_2->setText(QCoreApplication::translate("MainWindow", "\320\235\320\276\320\274\320\265\321\200:", nullptr));
        prod_numsearch_line_edit->setText(QString());
        shop_edit_button->setText(QCoreApplication::translate("MainWindow", "\320\240\320\265\320\264.", nullptr));
        menu->setTitle(QCoreApplication::translate("MainWindow", "\320\244\320\260\320\271\320\273", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
